language: "perl"
perl:
    - "5.14"
install: "echo"
before_script:
    - cpanm -n Test::Harness
script: "make test"
branches:
   only:
     - master
notifications:
  recipients:
    - chansen@cpan.org
  email:
    on_success: change
    on_failure: always
