language: "perl"
perl:
    - "5.14"
install: "perl -V"
before_script:
    - cpanm -n Test::Harness
script: "make test"
notifications:
  recipients:
    - chansen@cpan.org
  email:
    on_success: change
    on_failure: always
